language: java
jdk:
  - oraclejdk8
script:
  - ./gradlew build 
  - cd pojo-generator
  - ./gradlew build
after_success:
  - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
